version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.11 sudo -E sh; cd -; }
      - run:
          command: dagger call -m github.com/goreleaser/goreleaser@v2.3.2 call test output
