name: ci
on:
  push:
    branches: ["**"]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Dagger
        uses: dagger/dagger-for-github@v6
        with:
          module: github.com/goreleaser/goreleaser@12155a336baaa705e9363e3001c048238f15ff34
          args: test output
