name: ci
on:
  push:
    branches: ["phase2/**"]
jobs:
  ci:
    name: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Dagger
        uses: dagger/dagger-for-github@v7
        with:
          args: test
